### PR TITLE
Fix quadtree infinite recursion

### LINKED ISSUE #4: Quadtree descends into an infinite loop for similar data points
When building the quadtree from the data points, if two points have the same value on one or more axes, the quadtree continues to subdivide nodes, and descends into an infinite recursive loop.

This continues until all physics memory is consumed and the program is terminated by the user (or possibly a segfault occurs).

### PR DESCRIPTION
**Pull request by nicktrav**
Attempts to fix #4.

When two points have identical values on one or more of their axes, the quadtree descends into an infinite recursion.

Fix this by ensuring that the points are placed in opposite nodes on the given axis.

### CODE REVIEW

**Comment by cemoody** [comment]
Also, can you fix the merge conflicts?

**Comment by nicktrav** [comment]
Have fixed the merge conflicts. Think it was due to the names of the files changing.

Also, is there a way to explicitly call the cython methods in ```_barnes_hut_tsne.pyx```? It looks like the only publicly accessible method is ```gradient```.

I want to be able to write a small test that initializes a quadtree and then tries to insert two points into it.

**Comment by cemoody** [comment]
That's a great idea. You have to write a new 'def' (not 'cdef') function (eg 'make_check_tree') in the cython file. All of the other functions are explicitly 'nogil' to be as fast as possible.

**Comment by nicktrav** [comment]
Hey @cemoody - should be good to go after a review from you.

**Comment by cemoody** [comment]
Nice. Thanks Nick.

**Pull request merged**
